### ISSUE TITLE
launch with deeplink without type param fails

### ISSUE THREAD

**Issue by ctalkington** [MedievalApple/Media-Assistant#2]
The docs imply that you can send just `u` without `t` and have `t` default to `v` but this never loads the application for me.

I suspect it's the AND logic here:

https://github.com/MedievalApple/Media-Assistant/blob/eeea22e2d0ecb174ad72d21b80b05eec7bfe508f/source/main.brs#L32

**Comment by MedievalApple** [comment]
That does appear to be the cause of the issue you were running into. Ill do some tests and work on getting the fix pushed out to the store version this weekend.

**Comment by ctalkington** [comment]
all good, it didn't hurt to always send from HA side. The app may see an increase in usage now that the HA PR is released and docs will mention your application soon

**Comment by MedievalApple** [comment]
Sorry for the delay but I got the fixes pushed. It was the AND logic, it kept the `t` arg from defaulting to `v` if the `u` arg was sent without a `t` to both the `/input` and `/launch` endpoints.
